server.port: 9002

spring:
  main.banner-mode: "off"
  jackson.default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    path: /h2-console